'use strict';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>Number(x).toLocaleString('ru-RU',{maximumFractionDigits:2})+' ₸';let state=null;
function notice(s,error=false){$('#notice').textContent=s;$('#notice').classList.toggle('error',error);}
async function api(url,body){const csrf=document.cookie.split('; ').find(x=>x.startsWith('csrftoken='))?.slice(10)||'';const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRFToken':csrf}:{},body:body?JSON.stringify(body):undefined});let d;try{d=await r.json();}catch{throw Error('Сервер недоступен. Обновите страницу.');}if(!r.ok){let e=Error(d.error||'Не удалось выполнить действие');e.status=r.status;throw e;}return d;}
const fields=f=>Object.fromEntries(new FormData(f));
const status={open:'Приём предложений',selected:'Выбрано предложение',closed:'Закрыта'};
function proposal(p,r,buyer){return `<div class="proposal ${p.accepted?'selected':''}"><strong>${esc(p.company)}</strong><p><small>${p.verified?'Профиль проверен администратором':'Профиль не проверен'} · ${esc({manufacturer:'Производитель',distributor:'Дистрибьютор',seller:'Продавец'}[p.role])}</small></p><p>${money(p.unitPrice)} × ${r.quantity}<br>Доставка: ${money(p.delivery)}<br>Срок: ${p.days} дн.</p><strong class="total">${money(p.total)}</strong><p>${esc(p.terms)}</p><button class="secondary" data-download="${p.id}">Скачать условия</button>${buyer?`<button class="secondary" data-save="${p.companyId}">${state.saved.some(s=>s.company_id===p.companyId)?'★ Сохранена':'☆ Сохранить компанию'}</button>`:''}${p.accepted?'<strong>✓ Выбрано покупателем</strong>':buyer&&r.status==='open'?`<button class="primary" data-accept="${p.id}">Выбрать предложение</button>`:''}</div>`;}
function requestCard(r,buyer){return `<article class="business-card"><div class="request-head"><h3>№${r.id} · ${esc(r.title)}</h3><span>${status[r.status]}</span></div><p class="muted">${esc(r.category)} · ${r.quantity} ${esc(r.unit)} · ${esc(r.city)} · до ${r.deadline}</p><p>${esc(r.specifications)}</p>${r.buyerEmail?`<p>Контакт покупателя: ${esc(r.buyerEmail)}</p>`:''}<div class="proposal-grid">${r.proposals.map(p=>proposal(p,r,buyer)).join('')||'<p class="muted">Пока нет предложений.</p>'}</div>${!buyer&&r.status==='open'&&state.company?.myRole!=='viewer'?`<details><summary>${r.proposals.length?'Обновить предложение':'Предложить условия'}</summary><form data-proposal="${r.id}"><div class="form-grid"><label>Цена единицы с налогами, ₸<input name="unitPrice" type="number" min="0.01" max="1000000000" step="0.01" required></label><label>Доставка за партию, ₸<input name="delivery" type="number" min="0" max="1000000000" step="0.01" value="0" required></label><label>Срок поставки, дней<input name="days" type="number" min="1" max="365" step="1" required></label></div><label>Условия, срок действия цены и характеристики<textarea name="terms" maxlength="3000" required></textarea></label><button class="primary">Отправить предложение</button></form></details>`:''}${buyer?`<button class="secondary" data-repeat="${r.id}" style="margin-top:18px">Повторить закупку</button>`:''}${buyer&&r.status!=='closed'?`<button class="secondary" style="margin-top:18px" data-close="${r.id}">Закрыть запрос</button>`:''}</article>`;}
async function load(){try{state=await api('/api/business/');$('#workspace').hidden=false;$('#loginNeeded').hidden=true;$('#savedCompanies').innerHTML=state.saved.map(s=>`<p>${esc(s.company__name)} <button class="secondary" data-save="${s.company_id}">Убрать</button></p>`).join('')||'<p class="muted">Сохраняйте компании из полученных предложений.</p>';$('#rfqCategory').innerHTML=state.categories.map(c=>`<option value="${c.id}">${esc(c.name_ru)}</option>`).join('');$('#buyerRequests').innerHTML=state.mine.map(r=>requestCard(r,true)).join('')||'<p class="muted">Создайте первый запрос выше.</p>';$('#marketRequests').innerHTML=state.market.map(r=>requestCard(r,false)).join('')||'<p class="muted">Нет открытых запросов. Для доступа создайте профиль компании.</p>';$('#sellerResponses').innerHTML=state.responses.map(r=>requestCard(r,false)).join('')||'<p class="muted">История пока пуста.</p>';const c=state.company;$('#teamPanel').hidden=!c;$('#companyHeading').textContent=c?c.name+' · '+(c.verified?'Проверена':'Не проверена'):'Создать компанию';if(c){for(const key of ['name','city','role','website','description'])$('#companyForm').elements[key].value=c[key];for(const el of $('#companyForm').elements)el.disabled=c.myRole!=='owner';$('#members').innerHTML=c.members.map(m=>`<p>${esc(m.user__email)} · ${esc(m.role)}</p>`).join('');$('#memberForm').hidden=c.myRole!=='owner';}$('#unread').textContent=state.notifications.filter(n=>!n.read).length;$('#alerts').innerHTML=state.notifications.map(n=>`<div class="notification ${n.read?'':'unread'}">${esc(n.message)}</div>`).join('')||'<p>Новых уведомлений нет.</p>';}catch(e){if(e.status===401){$('#workspace').hidden=true;$('#loginNeeded').hidden=false;}else notice(e.message,true);}}
async function submit(action,body,button){button.disabled=true;try{await api('/api/business/'+action+'/',body);await load();notice('Сохранено.');return true;}catch(e){notice(e.message,true);return false;}finally{button.disabled=false;}}
$('#rfqForm').onsubmit=async e=>{e.preventDefault();const d=fields(e.target);if(await submit('rfq',{...d,category:Number(d.category),quantity:Number(d.quantity)},e.submitter))e.target.reset();};
$('#companyForm').onsubmit=e=>{e.preventDefault();submit('company',fields(e.target),e.submitter);};
$('#memberForm').onsubmit=e=>{e.preventDefault();submit('member',fields(e.target),e.submitter);};
document.addEventListener('submit',e=>{if(!e.target.dataset.proposal)return;e.preventDefault();const d=fields(e.target);submit('proposal',{...d,requestId:Number(e.target.dataset.proposal),days:Number(d.days)},e.submitter);});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){for(const s of ['buy','sell','alerts','plans'])$('#tab-'+s).hidden=s!==b.dataset.tab;for(const t of document.querySelectorAll('[data-tab]'))t.className=t===b?'primary':'secondary';}if(b.dataset.save)submit('save',{companyId:Number(b.dataset.save)},b);
if(b.dataset.repeat){const r=state.mine.find(x=>x.id===Number(b.dataset.repeat));for(const k of ['title','quantity','unit','city','specifications'])$('#rfqForm').elements[k].value=r[k];$('#rfqForm').elements.category.value=r.categoryId;$('#rfqForm').elements.deadline.value='';$('#rfqForm').scrollIntoView({behavior:'smooth'});notice('Запрос скопирован в форму. Укажите новый срок и опубликуйте.');}
if(b.dataset.download){let r,p;for(const x of [...state.mine,...state.market,...state.responses]){const found=x.proposals.find(z=>z.id===Number(b.dataset.download));if(found){r=x;p=found;break;}}if(p){const content=`FactoryDirect — условия предложения\nЗапрос №${r.id}: ${r.title}\nКомпания: ${p.company}\nКоличество: ${r.quantity} ${r.unit}\nЦена единицы: ${money(p.unitPrice)}\nДоставка: ${money(p.delivery)}\nВсего: ${money(p.total)}\nСрок: ${p.days} дней\nУсловия: ${p.terms}\n\nСнимок предложения, не счёт на оплату и не договор.`;const url=URL.createObjectURL(new Blob([content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='FactoryDirect-offer-'+p.id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}
if(b.dataset.accept){if(confirm('Выбрать это предложение? Компания получит ваш email для связи. Это не оплата и не заключение договора.'))submit('accept',{proposalId:Number(b.dataset.accept)},b);}if(b.dataset.close)submit('close',{requestId:Number(b.dataset.close)},b);});
$('#readAlerts').onclick=e=>submit('read',{},e.target);
(async()=>{try{await api('/api/auth/me/');await load();}catch(e){notice(e.message,true);}})();
