'use strict';
const EXTRA = {
ru:{heroBadge:'ОТ ИСТОЧНИКА — К ВАШЕМУ БИЗНЕСУ',heroTitle1:'Ближе к источнику.',heroTitle2:'Выгоднее закупка.',heroText:'Найдите производителя, сравните условия и узнайте стоимость с доставкой. Вся закупка — в одном понятном пространстве.',catalogTitle:'Начните с нужного товара',catalogSubtitle:'Выберите товар, изучите источник и сравните условия закупки.',trust1:'Прозрачные условия',trust2:'Цена с учётом объёма',trust3:'Доставка в расчёте',sourceRoute:'Путь товара',sceneCaption:'Обжарка → ваш бизнес',sceneMinimum:'Демо · от 30 кг · без доставки',savedOnly:'♡ Избранное',catalogStatus:'Демо-каталог · цены в тенге',exportQuote:'↓ Скачать расчёт CSV',sourceTitle:'Паспорт источника',sourceAction:'Изучить источник',sourceNote:'Это модель цепочки поставки. Реальный первоисточник, документы и происхождение товара пока не подтверждены.',sourceUnknown:'Документы не загружены · источник не подтверждён',sourceStep1:'Сырьё / фабрика',sourceStep2:'Предложение в каталоге',sourceStep3:'Ваш бизнес',sourceChecklist:'Что проверить перед закупкой',sourceChecks:'Юридическое название и БИН|Адрес производства и официальный сайт|Сертификаты и происхождение товара|Образец, договор и полная стоимость',found:'Товаров',deliveryExtra:'Доставка отдельно',minimum:'Мин. партия',offersLabel:'предложений',save:'В избранное',saved:'В избранном',reset:'Сбросить фильтры',verified:'демо',verifiedProfile:'Демонстрационный профиль',smartTitle:'Найдём подходящее предложение',smartSubtitle:'Укажите товар, объём и город. Сравните демонстрационные предложения по цене с доставкой и срокам.',exportEmpty:'Сначала добавьте товар в корзину',exportDone:'Расчёт скачан. Все цены демонстрационные.'},
kk:{heroBadge:'ӨНДІРУШІДЕН — БИЗНЕСІҢІЗГЕ',heroTitle1:'Өндірушіге жақын.',heroTitle2:'Тиімді сатып алу.',heroText:'Өндірушіні табыңыз, шарттарды салыстырыңыз және жеткізумен бірге құнын есептеңіз.',catalogTitle:'Қажетті тауардан бастаңыз',catalogSubtitle:'Тауарды таңдап, дереккөзін зерттеп, сатып алу шарттарын салыстырыңыз.',trust1:'Ашық шарттар',sourceRoute:'Тауар жолы',sceneCaption:'Қуыру → бизнесіңіз',sceneMinimum:'Демо · 30 кг бастап · жеткізусіз',savedOnly:'♡ Таңдаулылар',catalogStatus:'Демо-каталог · бағалар теңгемен',exportQuote:'↓ CSV есебін жүктеу',sourceTitle:'Дереккөз паспорты',sourceAction:'Дереккөзді зерттеу',sourceNote:'Бұл жеткізу тізбегінің үлгісі. Нақты дереккөз, құжаттар және тауардың шығу тегі расталмаған.',sourceUnknown:'Құжаттар жоқ · дереккөз расталмаған',sourceStep1:'Шикізат / фабрика',sourceStep2:'Каталогтағы ұсыныс',sourceStep3:'Сіздің бизнесіңіз',sourceChecklist:'Сатып алар алдында тексеріңіз',sourceChecks:'Заңды атауы және БСН|Өндіріс мекенжайы және ресми сайт|Сертификаттар және тауардың шығу тегі|Үлгі, келісімшарт және толық құны',found:'Тауарлар',deliveryExtra:'Доставка отдельно',deliveryExtra:'Жеткізу бөлек',minimum:'Мин. партия',offersLabel:'ұсыныс',save:'Таңдаулыға қосу',saved:'Таңдаулыда',reset:'Сүзгілерді тазарту',verified:'демо',verifiedProfile:'Демонстрациялық профиль',exportEmpty:'Алдымен себетке тауар қосыңыз',exportDone:'Есеп жүктелді. Бағалар демонстрациялық.'},
en:{heroBadge:'FROM THE SOURCE — TO YOUR BUSINESS',heroTitle1:'Closer to the source.',heroTitle2:'Better by the batch.',heroText:'Discover manufacturers, compare terms and see the cost including delivery. One clear space for your next purchase.',catalogTitle:'Start with what you need',catalogSubtitle:'Explore a product, understand its source and compare purchasing terms.',trust1:'Transparent terms',sourceRoute:'Product journey',sceneCaption:'Roastery → your business',sceneMinimum:'Demo · from 30 kg · delivery excluded',savedOnly:'♡ Saved',catalogStatus:'Demo catalog · prices in KZT',exportQuote:'↓ Download quote CSV',sourceTitle:'Source passport',sourceAction:'Explore source',sourceNote:'This is a model supply chain. The actual source, documents and product origin have not been verified.',sourceUnknown:'No documents uploaded · unverified source',sourceStep1:'Raw materials / factory',sourceStep2:'Catalog offer',sourceStep3:'Your business',sourceChecklist:'Check before purchasing',sourceChecks:'Legal name and business identifier|Production address and official website|Certificates and product origin|Sample, contract and full cost',found:'Products',deliveryExtra:'Delivery extra',minimum:'Min. order',offersLabel:'offers',save:'Save product',saved:'Saved product',reset:'Reset filters',verified:'demo',verifiedProfile:'Demonstration profile',exportEmpty:'Add a product to your cart first',exportDone:'Quote downloaded. All prices are illustrative.'}
};
Object.keys(EXTRA).forEach(l=>Object.assign(I18N[l],EXTRA[l]));
let favorites=[];
try { const v=JSON.parse(localStorage.getItem('fd-favorites')||'[]'); favorites=Array.isArray(v)?v.filter(id=>PRODUCTS.some(p=>p.id===id)):[]; } catch {}
let onlyFavorites=false;
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];localStorage.setItem('fd-favorites',JSON.stringify(favorites));renderProducts();}
renderProducts=function(){
 const q=($('#catalogSearch').value||'').trim().toLowerCase(),cat=$('#categoryFilter').value||'all',sort=$('#sortFilter').value;
 let rows=PRODUCTS.filter(p=>(cat==='all'||p.category===cat)&&(!onlyFavorites||favorites.includes(p.id))&&`${Object.values(p.name).join(' ')} ${p.offers.map(o=>makerById(o.maker).name).join(' ')}`.toLowerCase().includes(q)).map(p=>({p,best:bestOfferForProduct(p)}));
 if(sort==='price')rows.sort((a,b)=>a.best.unitPrice-b.best.unitPrice);
 if(sort==='saving')rows.sort((a,b)=>(b.p.retail-b.best.unitPrice)-(a.p.retail-a.best.unitPrice));
 $('#productGrid').innerHTML=rows.map(({p,best})=>{const min=Math.max(best.maker.minOrder,best.offer.tiers[0][0]);return `<article class="product-card"><div class="product-visual art-${p.id}"><span class="product-badge">${t(p.category)}</span><button class="favorite-btn ${favorites.includes(p.id)?'is-saved':''}" onclick="toggleFavorite('${p.id}')" aria-label="${favorites.includes(p.id)?t('saved'):t('save')}" aria-pressed="${favorites.includes(p.id)}">${favorites.includes(p.id)?'♥':'♡'}</button><img src="assets/${p.id}.svg" alt="" loading="lazy"></div><div class="product-body"><div class="product-meta"><span>${escapeHtml(cityName(best.maker.city))}</span><span>${p.offers.length} ${t('offersLabel')}</span></div><h3>${escapeHtml(p.name[lang])}</h3><button class="source-link" onclick="openSource('${p.id}')">${escapeHtml(best.maker.name)} ↗</button><div class="product-price"><strong>${formatPrice(best.unitPrice)}</strong><span>/ ${escapeHtml(p.unit[lang])}</span></div><div class="product-tier">${t('minimum')}: ${min} · ${t('deliveryExtra')}</div><div class="product-actions"><button class="primary" onclick="quickAdd('${p.id}')">+ ${t('add')}</button><button class="details-btn" onclick="openProduct('${p.id}')" aria-label="${t('details')}">↗</button></div><button class="source-bottom" onclick="openSource('${p.id}')">${t('sourceAction')} <span>→</span></button></div></article>`}).join('');
 $('#catalogEmpty').classList.toggle('hidden',rows.length>0);
 $('#resultCount').textContent=`${t('found')}: ${rows.length} / ${PRODUCTS.length}`;
 $('#savedCount').textContent=favorites.length;
 $('#favoritesOnly').setAttribute('aria-pressed',String(onlyFavorites));
 $('#categoryPills').innerHTML=['all','food','clothing','home','tech','packaging','construction'].map(c=>`<button class="category-pill ${cat===c?'active':''}" aria-pressed="${cat===c}" onclick="setCategory('${c}')">${t(c==='all'?'allCategories':c)}</button>`).join('');
};
function setCategory(c){$('#categoryFilter').value=c;renderProducts();}
function openSource(id){const p=productById(id);$('#productModalContent').innerHTML=`<span class="eyebrow">${t('sourceTitle')}</span><h2 id="productModalTitle">${escapeHtml(p.name[lang])}</h2><div class="source-warning">${t('sourceUnknown')}</div><div class="source-flow"><div><b>01</b>${t('sourceStep1')}<small>?</small></div><span>→</span><div><b>02</b>${t('sourceStep2')}<small>${p.offers.length} ${t('offersLabel')}</small></div><span>→</span><div><b>03</b>${t('sourceStep3')}<small>✓</small></div></div><p class="muted">${t('sourceNote')}</p><div class="source-makers">${p.offers.map(o=>{const m=makerById(o.maker);return `<button class="secondary" onclick="closeModal('productModal');openManufacturer('${m.id}')">${escapeHtml(m.name)} · ${escapeHtml(cityName(m.city))} ↗</button>`}).join('')}</div><h3>${t('sourceChecklist')}</h3><div class="source-checks">${t('sourceChecks').split('|').map(s=>`<label><input type="checkbox"> ${s}</label>`).join('')}</div>`;openModal('productModal');}
function exportQuote(){if(!cart.length){showToast(t('exportEmpty'));return;}const rows=[['DEMO — illustrative prices, not a commercial offer'],[t('product'),t('supplier'),t('quantity'),t('destination'),t('tableUnit'),t('goods'),t('delivery'),t('total')]];for(const item of cart){const p=productById(item.productId),o=p.offers.find(o=>o.maker===item.makerId),x=offerCalc(p,o,item.qty,item.destination,item.mode);rows.push([p.name[lang],x.maker.name,item.qty,cityName(item.destination),x.unitPrice,x.goods,x.delivery,x.total]);}const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='FactoryDirect-demo-quote.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(t('exportDone'));}
document.addEventListener('DOMContentLoaded',()=>{
 $('#favoritesOnly').addEventListener('click',()=>{onlyFavorites=!onlyFavorites;renderProducts();});
 $('#exportCart').addEventListener('click',exportQuote);
 const reset=document.createElement('button');reset.className='secondary';reset.dataset.i18n='reset';reset.textContent=t('reset');reset.onclick=()=>{$('#catalogSearch').value='';$('#categoryFilter').value='all';onlyFavorites=false;renderProducts();};$('#catalogEmpty').append(reset);
 // Keep keyboard focus in the active dialog and restore it on close.
 document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const modal=$('.modal:not(.hidden)');if(!modal)return;const nodes=$$('button,a[href],input,select,textarea,[tabindex="0"]',modal).filter(n=>!n.disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
});
const baseOpenModal=openModal,baseCloseModal=closeModal;let lastFocus=null;
openModal=function(id){if(!$('.modal:not(.hidden)'))lastFocus=document.activeElement;baseOpenModal(id);};
closeModal=function(id){baseCloseModal(id);if(!$('.modal:not(.hidden)'))lastFocus?.focus();};
window.closeModal=closeModal;
