'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('ru-RU')+' ₸';
let registering=false;
function message(text,error=false){$('#message').textContent=text;$('#message').classList.toggle('error',error);}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});let data;try{data=await response.json();}catch{throw Error('Запустите python3 server/app.py и откройте http://127.0.0.1:8001/seller.html');}if(!response.ok){const e=Error(data.error||'Ошибка сервера');e.status=response.status;throw e;}return data;}
function fields(form){return Object.fromEntries(new FormData(form));}
function mode(register){registering=register;$('#companyFields').hidden=!register;$('#companyFields').disabled=!register;$('#authSubmit').textContent=register?'Создать аккаунт':'Войти';$('#authForm [name=password]').autocomplete=register?'new-password':'current-password';$('#loginTab').setAttribute('aria-pressed',String(!register));$('#registerTab').setAttribute('aria-pressed',String(register));}
async function load(){try{const data=await api('/api/seller/me');$('#authPanel').hidden=true;$('#dashboard').hidden=false;$('#companyName').textContent=data.manufacturer.name;for(const name of ['name','city','role','sourceUrl'])$('#profileForm').elements[name].value=data.manufacturer[name]||'';$('#profileForm').elements.description.value=data.manufacturer.description.ru;$('#productCount').textContent=data.products.length;$('#requestCount').textContent=data.requests.length;$('#requestTotal').textContent=money(data.requests.reduce((s,x)=>s+x.total,0));$('#myProducts').innerHTML=data.products.length?data.products.map(p=>`<div class="inventory-row"><div><strong>${esc(p.name.ru)}</strong><small>Партия от ${p.minimum} ${esc(p.unit.ru)}</small></div><strong>${money(p.price)}</strong></div>`).join(''):'<p class="empty-seller">Пока нет товаров. Добавьте первое предложение выше.</p>';const states={received:'Получена',processing:'В работе',completed:'Завершена',declined:'Отклонена'};$('#myRequests').innerHTML=data.requests.length?data.requests.map(r=>`<article class="request-card"><div class="dashboard-top"><strong>${esc(r.id)}</strong><select aria-label="Статус ${esc(r.id)}" data-request="${esc(r.id)}">${Object.entries(states).map(([v,n])=>`<option value="${v}" ${r.status===v?'selected':''}>${n}</option>`).join('')}</select></div><p class="small muted">${esc(r.createdAt)} UTC · ${esc(r.contact)}</p>${r.items.map(i=>`<div class="inventory-row"><span>${esc(i.productName.ru)} × ${i.qty}</span><strong>${money(i.total)}</strong></div>`).join('')}<p>Ваши позиции с доставкой: <strong>${money(r.total)}</strong></p></article>`).join(''):'<p class="empty-seller">Пока нет заявок. Покупатели смогут оставить их из каталога.</p>';}catch(e){if(e.status===401){$('#authPanel').hidden=false;$('#dashboard').hidden=true;}else throw e;}}
async function submit(form,path,transform=x=>x){const button=form.querySelector('button[type=submit],button:not([type])');button.disabled=true;try{await api(path,transform(fields(form)));await load();message('Сохранено.');if(form.id==='productForm')form.reset();if(form.id==='authForm')form.elements.password.value='';}catch(e){message(e.message,true);}finally{button.disabled=false;}}
$('#loginTab').onclick=()=>mode(false);$('#registerTab').onclick=()=>mode(true);
$('#authForm').onsubmit=e=>{e.preventDefault();submit(e.target,registering?'/api/auth/register':'/api/auth/login');};
$('#profileForm').onsubmit=e=>{e.preventDefault();submit(e.target,'/api/seller/profile');};
$('#productForm').onsubmit=e=>{e.preventDefault();submit(e.target,'/api/seller/products',x=>({...x,price:Number(x.price),minimum:Number(x.minimum)}));};
$('#logout').onclick=async()=>{try{await api('/api/auth/logout',{});await load();message('Вы вышли из кабинета.');}catch(e){message(e.message,true);}};
$('#refresh').onclick=()=>load().then(()=>message('Заявки обновлены.')).catch(e=>message(e.message,true));
$('#myRequests').onchange=async e=>{if(!e.target.dataset.request)return;e.target.disabled=true;try{await api('/api/seller/status',{requestId:e.target.dataset.request,status:e.target.value});message('Статус сохранён.');}catch(error){message(error.message,true);await load();}finally{e.target.disabled=false;}};
(async()=>{try{const data=await api('/api/catalog');for(const el of document.querySelectorAll('.cities'))el.innerHTML=Object.entries(data.cities).map(([id,n])=>`<option value="${esc(id)}">${esc(n.ru)}</option>`).join('');await load();}catch(e){message('Кабинет недоступен. '+e.message,true);}})();
