'use strict';
let sourceListings=SOURCE_SNAPSHOT;
let sourceSelection=[];
const SOURCE_TEXT={
ru:{nav:'Источники',eyebrow:'РЕАЛЬНЫЕ КОМПАНИИ · УПАКОВКА',title:'Найдите, кто производит',subtitle:'Шесть позиций с сайтов пяти компаний. Откройте источник и уточните условия напрямую.',disclaimer:'Проверены страницы сайтов, а не юридический статус и сертификаты. Компании не подключены к FactoryDirect; заказы им отсюда не отправляются.',search:'Товар, компания или город',all:'Вся упаковка',boxes:'Гофрокоробки',cups:'Бумажная посуда',compare:'Сравнить',select:'В сравнение',request:'По запросу',from:'от',minimum:'Мин. партия',unknown:'Уточнить',passport:'Паспорт источника',website:'Сайт компании ↗',status:'Производитель — по заявлению сайта',reviewed:'Страница проверена',empty:'Нет совпадений. Измените запрос или категорию.',clear:'Сбросить',choose:'Выберите от 2 до 3 позиций',limit:'Можно сравнить до 3 позиций.',terms:'Условия со страницы',claim:'Что подтверждает источник',limits:'Что ещё уточнить',source:'Страница товара',evidence:'Заявление о производстве',notverified:'Документы и юридический статус не проверены. Наличие сайта не подтверждает происхождение конкретной партии.',price:'Опубликованная цена',caution:'Разные размеры и конструкции не равнозначны. Цены «от» нельзя считать итоговой стоимостью; доставка и наличие не подтверждены.',count:'Позиций',draft:'Подготовить запрос цены',copy:'Скачать текст запроса',draftnote:'Это черновик для самостоятельной отправки. FactoryDirect никому его не отправляет.',demoCatalog:'Учебный каталог и товары кабинета',ribbon:'Источники компаний — по открытым сайтам. Расчёты доставки — демонстрационные.'},
kk:{nav:'Дереккөздер',eyebrow:'НАҚТЫ КОМПАНИЯЛАР · ҚАПТАМА',title:'Өндірушіні табыңыз',subtitle:'Бес компанияның сайтынан алты позиция. Шарттарды компаниядан нақтылаңыз.',disclaimer:'Сайт беттері қаралды; заңды мәртебе мен сертификаттар тексерілмеген. Компаниялар FactoryDirect жүйесіне қосылмаған.',search:'Тауар, компания немесе қала',all:'Барлық қаптама',boxes:'Гофроқораптар',cups:'Қағаз ыдыс',compare:'Салыстыру',select:'Салыстыруға',request:'Сұраныс бойынша',from:'бастап',minimum:'Мин. партия',unknown:'Нақтылау керек',passport:'Дереккөз паспорты',website:'Компания сайты ↗',status:'Сайт мәліметі бойынша өндіруші',reviewed:'Бет қаралды',empty:'Ештеңе табылмады. Сұрауды өзгертіңіз.',clear:'Тазарту',choose:'2–3 позиция таңдаңыз',limit:'3 позицияға дейін салыстыруға болады.',terms:'Сайттағы шарттар',claim:'Дереккөз мәліметі',limits:'Нақтылау қажет',source:'Тауар беті',evidence:'Өндіріс туралы мәлімет',notverified:'Құжаттар мен заңды мәртебе тексерілмеген. Сайт тауар партиясының шығу тегін растамайды.',price:'Жарияланған баға',caution:'Өлшемдер мен құрылымдар әртүрлі. Бастапқы баға толық құн емес; жеткізу мен қолжетімділікті нақтылау керек.',count:'Позициялар',draft:'Баға сұрауын дайындау',copy:'Сұрау мәтінін жүктеу',draftnote:'Өзіңіз жіберуге арналған жоба. FactoryDirect оны жібермейді.',demoCatalog:'Оқу каталогы және кабинет тауарлары',ribbon:'Компания деректері ашық сайттардан. Жеткізу есебі демонстрациялық.'},
en:{nav:'Sources',eyebrow:'REAL COMPANIES · PACKAGING',title:'Find who makes it',subtitle:'Six listings from five company websites. Check the source and confirm terms directly.',disclaimer:'Website pages reviewed; legal status and certificates not verified. These companies are not connected to FactoryDirect.',search:'Product, company or location',all:'All packaging',boxes:'Corrugated boxes',cups:'Paper tableware',compare:'Compare',select:'Compare this',request:'On request',from:'from',minimum:'Min. order',unknown:'Confirm directly',passport:'Source passport',website:'Company website ↗',status:'Manufacturer — website claim',reviewed:'Page reviewed',empty:'No results. Change your search or category.',clear:'Reset',choose:'Select 2–3 listings',limit:'Compare up to 3 listings.',terms:'Published terms',claim:'Source evidence',limits:'Confirm before ordering',source:'Product page',evidence:'Manufacturing claim',notverified:'Documents and legal status have not been verified. A website does not establish the origin of a particular batch.',price:'Published price',caution:'Different dimensions and constructions are not equivalent. Starting prices are not final quotes; delivery and availability remain unconfirmed.',count:'Listings',draft:'Prepare price inquiry',copy:'Download inquiry text',draftnote:'A draft for you to send yourself. FactoryDirect does not send it.',demoCatalog:'Sample catalog and seller listings',ribbon:'Company sources from public websites. Delivery calculations are illustrative.'}
};
const st=k=>SOURCE_TEXT[lang][k];
for(const l of Object.keys(SOURCE_TEXT)){I18N[l].navSources=SOURCE_TEXT[l].nav;I18N[l].demoDataNote=SOURCE_TEXT[l].ribbon;I18N[l].catalogTitle=SOURCE_TEXT[l].demoCatalog;}
function sourcePrice(x){return x.priceFrom===null?st('request'):`${st('from')} ${formatPrice(x.priceFrom)}`;}
function sourceLink(url,label){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return '';return `<a href="${escapeHtml(u.href)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)}</a>`;}catch{return '';}}
function renderSources(){
 document.querySelectorAll('[data-source-text]').forEach(n=>n.textContent=st(n.dataset.sourceText));
 $('#sourceSearch').placeholder=st('search');
 for(const o of $('#sourceCategory').options)o.textContent=st(o.value);
 $('#sourceCompareButton').textContent=`${st('compare')} (${sourceSelection.length}/3)`;
 const q=$('#sourceSearch').value.trim().toLowerCase(),category=$('#sourceCategory').value;
 const rows=sourceListings.filter(x=>(category==='all'||x.category===category)&&`${x.name} ${x.company} ${x.city}`.toLowerCase().includes(q));
 $('#sourceCount').textContent=`${st('count')}: ${rows.length}`;
 $('#sourceGrid').innerHTML=rows.length?rows.map(x=>`<article class="product-card source-card"><div class="source-card-top"><span>${x.category==='boxes'?'▧':'◡'}</span><small>${escapeHtml(x.company)}</small></div><div class="product-body"><small class="muted">${escapeHtml(x.city)}</small><h3>${escapeHtml(x.name)}</h3><p class="source-price">${sourcePrice(x)}</p><p class="small muted">${st('minimum')}: ${x.minimum===null?st('unknown'):x.minimum}</p><span class="source-status">${st('status')}</span><small class="muted">${st('reviewed')}: ${x.checkedAt}</small><button class="primary" data-source-id="${x.id}">${st('passport')} ↗</button><label class="source-select"><input type="checkbox" data-compare-id="${x.id}" ${sourceSelection.includes(x.id)?'checked':''}> ${st('select')}</label></div></article>`).join(''):`<p class="empty-state">${st('empty')} <button class="secondary" id="sourceReset">${st('clear')}</button></p>`;
 if(!$('#sourceComparison').hidden)renderSourceComparison();
}
function toggleSource(id,checked){if(checked&&sourceSelection.length>=3){showToast(st('limit'));renderSources();return;}sourceSelection=checked?[...sourceSelection,id]:sourceSelection.filter(x=>x!==id);renderSources();}
function openSourcePassport(id){const x=sourceListings.find(x=>x.id===id);if(!x)return;
 $('#productModalContent').innerHTML=`<p class="eyebrow">${st('passport')}</p><h2 id="productModalTitle">${escapeHtml(x.name)}</h2><p>${escapeHtml(x.company)} · ${escapeHtml(x.city)}</p><div class="source-warning">${st('status')}<br>${st('reviewed')}: ${x.checkedAt}</div><h3>${st('claim')}</h3><p>${escapeHtml(x.claim)}</p>${sourceLink(x.evidenceUrl,st('evidence')+' ↗')}<h3>${st('terms')}</h3><p>${sourcePrice(x)} · ${st('minimum')}: ${x.minimum===null?st('unknown'):x.minimum}</p><p>${escapeHtml(x.terms)}</p><h3>${st('limits')}</h3><p>${escapeHtml(x.note)}</p><p class="muted">${st('notverified')}</p><div class="source-makers">${sourceLink(x.sourceUrl,st('source')+' ↗')}<button class="secondary" id="sourceDraft" data-id="${x.id}">${st('draft')}</button></div>`;
 openModal('productModal');
}
function renderSourceComparison(){const rows=sourceListings.filter(x=>sourceSelection.includes(x.id));$('#sourceComparison').innerHTML=`<h3>${st('compare')}</h3><p class="muted">${st('caution')}</p><div class="table-wrap"><table><thead><tr><th></th>${rows.map(x=>`<th>${escapeHtml(x.company)}<br><small>${escapeHtml(x.name)}</small></th>`).join('')}</tr></thead><tbody>${[[st('price'),x=>sourcePrice(x)],[st('minimum'),x=>x.minimum===null?st('unknown'):x.minimum],[st('terms'),x=>escapeHtml(x.terms)],[st('limits'),x=>escapeHtml(x.note)],[st('source'),x=>sourceLink(x.sourceUrl,st('website'))]].map(([label,fn])=>`<tr><th>${label}</th>${rows.map(x=>`<td>${fn(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function draftSource(id){const x=sourceListings.find(x=>x.id===id);const text=`Здравствуйте, ${x.company}!\n\nИнтересует: ${x.name}.\nИсточник: ${x.sourceUrl}\n\nНужное количество: [укажите]\nРазмер / объём / материал: [укажите]\nГород доставки: [укажите]\n\nПрошу уточнить цену с НДС, минимальную партию, наличие, сроки изготовления, стоимость доставки и возможность получить образец.\nПодтвердите, пожалуйста, являетесь ли вы производителем этой позиции, и предоставьте реквизиты и документы о происхождении.\n\nКонтакт для ответа: [укажите]\n`;
 $('#productModalContent').innerHTML=`<h2 id="productModalTitle">${st('draft')}</h2><p>${st('draftnote')}</p><textarea id="inquiryDraft" aria-label="Inquiry" rows="13"></textarea><button id="downloadInquiry" class="primary">${st('copy')}</button>`;$('#inquiryDraft').value=text;$('#downloadInquiry').onclick=()=>{const blob=new Blob([$('#inquiryDraft').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='FactoryDirect-inquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#inquiryDraft').focus();}
document.addEventListener('DOMContentLoaded',async()=>{
 renderSources();$('#sourceSearch').addEventListener('input',renderSources);$('#sourceCategory').addEventListener('change',renderSources);$('#languageSelect').addEventListener('change',renderSources);
 $('#sourceGrid').addEventListener('click',e=>{const b=e.target.closest('[data-source-id]');if(b)openSourcePassport(b.dataset.sourceId);if(e.target.id==='sourceReset'){$('#sourceSearch').value='';$('#sourceCategory').value='all';renderSources();}});
 $('#sourceGrid').addEventListener('change',e=>{if(e.target.dataset.compareId)toggleSource(e.target.dataset.compareId,e.target.checked);});
 $('#sourceCompareButton').onclick=()=>{if(sourceSelection.length<2){showToast(st('choose'));return;}$('#sourceComparison').hidden=false;renderSourceComparison();$('#sourceComparison').scrollIntoView({behavior:'smooth'});};
 $('#productModalContent').addEventListener('click',e=>{if(e.target.id==='sourceDraft')draftSource(e.target.dataset.id);});
 if(location.protocol!=='file:'){try{const r=await fetch('/api/sources',{signal:AbortSignal.timeout(4000)});if(r.ok){const data=await r.json();if(Array.isArray(data.listings)&&data.listings.length)sourceListings=data.listings;renderSources();}}catch{}}
});
