# Generated by Django 5.2.17 on 2026-09-28 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=80, verbose_name='название (RU)')),
                ('name_kk', models.CharField(max_length=80, verbose_name='название (KZ)')),
                ('name_en', models.CharField(max_length=80, verbose_name='название (EN)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Латиницей, например almaty. Используется в ссылках и расчётах.', unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=80, verbose_name='название (RU)')),
                ('name_kk', models.CharField(max_length=80, verbose_name='название (KZ)')),
                ('name_en', models.CharField(max_length=80, verbose_name='название (EN)')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lng', models.FloatField(verbose_name='долгота')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_price', models.PositiveIntegerField(default=2500, verbose_name='доставка внутри города, ₸')),
                ('base_price', models.PositiveIntegerField(default=3500, verbose_name='межгород: фиксированная часть, ₸')),
                ('per_km', models.DecimalField(decimal_places=2, default=2.2, max_digits=6, verbose_name='межгород: за километр, ₸')),
                ('per_weight_unit', models.DecimalField(decimal_places=2, default=7, max_digits=6, verbose_name='межгород: за единицу товара × коэффициент веса, ₸')),
                ('express_multiplier', models.DecimalField(decimal_places=2, default=1.75, max_digits=4, verbose_name='экспресс: множитель цены')),
                ('express_eta_factor', models.DecimalField(decimal_places=2, default=0.62, max_digits=4, verbose_name='экспресс: множитель срока')),
                ('km_per_day', models.PositiveIntegerField(default=650, verbose_name='км в день в пути')),
                ('unknown_distance_km', models.PositiveIntegerField(default=1000, verbose_name='расстояние, если нет в таблице, км')),
            ],
            options={
                'verbose_name': 'тарифы доставки',
                'verbose_name_plural': 'тарифы доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='статус')),
                ('company', models.CharField(max_length=200, verbose_name='компания')),
                ('bin', models.CharField(blank=True, max_length=12, verbose_name='БИН')),
                ('contact_person', models.CharField(max_length=200, verbose_name='контактное лицо')),
                ('contact', models.CharField(max_length=200, verbose_name='телефон или e-mail')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('language', models.CharField(default='ru', max_length=2, verbose_name='язык сайта')),
                ('goods_total', models.PositiveBigIntegerField(default=0, verbose_name='товары, ₸')),
                ('delivery_total', models.PositiveBigIntegerField(default=0, verbose_name='доставка, ₸')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='итого, ₸')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Латиницей. Используется в адресе страницы производителя.', unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('initials', models.CharField(max_length=3, verbose_name='инициалы для логотипа')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='рейтинг')),
                ('min_order', models.PositiveIntegerField(verbose_name='минимальный заказ')),
                ('dispatch_days', models.PositiveIntegerField(verbose_name='отгрузка, дней')),
                ('description_ru', models.TextField(verbose_name='описание (RU)')),
                ('description_kk', models.TextField(verbose_name='описание (KZ)')),
                ('description_en', models.TextField(verbose_name='описание (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('categories', models.ManyToManyField(related_name='manufacturers', to='marketplace.category', verbose_name='категории')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturers', to='marketplace.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Латиницей. Используется в адресе страницы товара.', unique=True, verbose_name='код')),
                ('icon', models.CharField(max_length=8, verbose_name='иконка (эмодзи)')),
                ('name_ru', models.CharField(max_length=120, verbose_name='название (RU)')),
                ('name_kk', models.CharField(max_length=120, verbose_name='название (KZ)')),
                ('name_en', models.CharField(max_length=120, verbose_name='название (EN)')),
                ('unit_ru', models.CharField(max_length=20, verbose_name='единица (RU)')),
                ('unit_kk', models.CharField(max_length=20, verbose_name='единица (KZ)')),
                ('unit_en', models.CharField(max_length=20, verbose_name='единица (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='описание (RU)')),
                ('description_kk', models.TextField(blank=True, verbose_name='описание (KZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='описание (EN)')),
                ('retail_price', models.PositiveIntegerField(help_text='Для сравнения «экономия против розницы».', verbose_name='розничная цена, ₸')),
                ('weight_factor', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='коэффициент веса для доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, verbose_name='товар')),
                ('manufacturer_name', models.CharField(max_length=120, verbose_name='производитель')),
                ('destination_name', models.CharField(max_length=80, verbose_name='город доставки')),
                ('delivery_mode', models.CharField(choices=[('standard', 'Стандарт'), ('express', 'Экспресс'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='способ доставки')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('unit_price', models.PositiveIntegerField(verbose_name='цена за единицу, ₸')),
                ('goods', models.PositiveBigIntegerField(verbose_name='товар, ₸')),
                ('delivery', models.PositiveBigIntegerField(verbose_name='доставка, ₸')),
                ('total', models.PositiveBigIntegerField(verbose_name='итого, ₸')),
                ('eta_days', models.PositiveIntegerField(verbose_name='срок, дней')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.city', verbose_name='город доставки')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.manufacturer', verbose_name='производитель')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order', verbose_name='заявка')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='marketplace.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.PositiveIntegerField(help_text='Цена за единицу, пока не достигнут первый уровень объёма.', verbose_name='базовая цена, ₸')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.manufacturer', verbose_name='производитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения (цены)',
                'ordering': ['product', 'manufacturer'],
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField(verbose_name='расстояние, км')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='marketplace.city', verbose_name='откуда')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='marketplace.city', verbose_name='куда')),
            ],
            options={
                'verbose_name': 'расстояние',
                'verbose_name_plural': 'расстояния',
                'ordering': ['from_city', 'to_city'],
                'constraints': [models.UniqueConstraint(fields=('from_city', 'to_city'), name='unique_distance_pair')],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(verbose_name='от количества')),
                ('unit_price', models.PositiveIntegerField(verbose_name='цена за единицу, ₸')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='marketplace.offer', verbose_name='предложение')),
            ],
            options={
                'verbose_name': 'уровень цены',
                'verbose_name_plural': 'уровни цены',
                'ordering': ['min_qty'],
                'constraints': [models.UniqueConstraint(fields=('offer', 'min_qty'), name='unique_tier_qty')],
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('product', 'manufacturer'), name='unique_offer'),
        ),
    ]
